### ISSUE TITLE
update_command does not default properly

### ISSUE THREAD

**Issue by atombaby** [FredHutch/remote-certs#1]
Throws the following error if not set:

```
       NoMethodError
       -------------
       undefined method `[]' for nil:NilClass

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/remote-certs/recipes/default.rb:9:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/remote-certs/recipes/default.rb:8:in `from_file'
         /tmp/kitchen/cache/cookbooks/cit-roles/recipes/base.rb:19:in `from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/remote-certs/recipes/default.rb:

         2:  # Cookbook Name:: remote-certs
         3:  # Recipe:: default
         4:  #
         5:  # Copyright (c) 2016 The Authors, All Rights Reserved.
         6:  # 
         7:  
         8:  execute 'install_cert' do
         9>>     command node['certs']['update_command']
        10:      action :nothing
        11:  end
        12:  
        13:  # create organization subdirectory for certificate
        14:  directory "/usr/share/ca-certificates/#{node['certs']['organization']}" do
        15:      owner 'root'
        16:      group 'root'
        17:      mode '0755'
        18:      action :create

       Platform:
       ---------
       x86_64-linux


       Running handlers:
       [2016-05-04T22:02:17+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-05-04T22:02:17+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 11 seconds
       [2016-05-04T22:02:17+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-05-04T22:02:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-05-04T22:02:17+00:00] ERROR: undefined method `[]' for nil:NilClass
       [2016-05-04T22:02:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by atombaby** [comment]
Fixed in e9f70cb
